# To understand how to use the build/config system, read the docs in docs/build.md.

webhookVersion: 104.0.0+up0.5.0-rc8
provisioningCAPIVersion: 104.0.0+up0.2.0
cspAdapterMinVersion: 104.0.0+up4.0.0-rc8
defaultShellVersion: rancher/shell:v0.2.1-rc.4
fleetVersion: 104.0.0+up0.10.0-rc.16
systemChartDefaultBranch: dev-v2.9
chartDefaultBranch: dev-v2.9
kdmBranch: dev-v2.9